version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: 'task'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/task
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      
      # Enhanced security and CORS settings
      KC_SPI_CORS_ENABLED: "true"
      KC_SPI_CORS_ALLOW_CREDENTIALS: "true"
      KC_SPI_CORS_ALLOW_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
      KC_SPI_CORS_ALLOW_HEADERS: "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization"
      KC_SPI_CORS_ALLOW_ORIGINS: "http://localhost:3000,http://localhost:5173"
      KC_SPI_CORS_EXPOSED_HEADERS: "WWW-Authenticate,Authorization"
      KC_SPI_CORS_MAX_AGE: "3600"
      
      # Security headers
      KC_SPI_CONTENT_SECURITY_POLICY_DEFAULT_HEADER: "frame-ancestors 'self' http://localhost:3000 http://localhost:5173; frame-src 'self' http://localhost:3000 http://localhost:5173; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' http://localhost:8180 http://localhost:3000 http://localhost:5173"
      
      # Web Origins
      KC_SPI_WEB_ORIGINS_ALLOWED_ORIGINS: "+http://localhost:3000 http://localhost:5173"
      
      # Cache config for better performance
      KC_CACHE: "local"
      
      # HTTP settings
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_PROXY_ADDRESS_FORWARDING: "true"
    command: [
      "start-dev",
      "--http-enabled=true",
      "--hostname=localhost",
      "--hostname-strict=false",
      "--proxy=edge",
      "--features=token-exchange,admin-fine-grained-authz,scripts"
    ]
    ports:
      - "8180:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - keycloak_data:/opt/keycloak/data/
      - keycloak_themes:/opt/keycloak/themes/

volumes:
  keycloak_data:
  keycloak_themes:
  my-db:
    driver: local

networks:
  backend:
    driver: bridge
