version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'task'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    restart: always
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/task
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      KC_FEATURES: "token-exchange,admin-fine-grained-authz"
      KC_SPI_CONNECTIONS_HTTP_DEFAULT_ALLOWED_ORIGINS: "http://localhost:3000"
      KC_SPI_CONNECTIONS_HTTP_DEFAULT_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KC_SPI_CONNECTIONS_HTTP_DEFAULT_ALLOW_CREDENTIALS: "true"
      KC_SPI_CONNECTIONS_HTTP_DEFAULT_EXPOSED_HEADERS: "Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Authorization"
      KC_HOSTNAME: "localhost:8180"
      KC_HTTP_RELATIVE_PATH: "/"
      KC_HTTP_PORT: "8180"
    command: [
      "start-dev",
      "--hostname=localhost",
      "--hostname-port=8180",
      "--http-enabled=true",
      "--http-port=8080",
      "--proxy=edge",
      "--spi-connections-http-allowed-origins=http://localhost:3000"
    ]
    ports:
      - "8180:8080"
    depends_on:
      - db
    networks:
      backend:
        aliases:
          - "keycloak"
    volumes:
      - keycloak_data:/opt/keycloak/data/
      - ./keycloak-config:/opt/keycloak/conf

volumes:
  keycloak_data:
  my-db:

networks:
  backend:
    driver: bridge
