CREATE TABLE task (
    id SERIAL PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
    owner VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
